id = "rayslash.currency"
name = "Currency"
description = "Convert currencies with cached live rates."
author = "rayslash"
license = "MIT"
kind = "wasm"
repository = "https://github.com/rslauncher/rayslash-module-currency"
official = true
review_status = "reviewed"
github_stars = 0
updated_at = "2026-07-26T23:42:46Z"

[[versions]]
version = "1.0.1"
api_version = "^1.0"
source_commit = "e15bc9b368ed3d8af584e285153994340e0f381f"
asset_url = "https://github.com/rslauncher/rayslash-module-currency/releases/download/v1.0.1/rayslash.currency-1.0.1.tar.zst"
sha256 = "38a4555d7308cd92e5dfb1a377470a8f699e73cd20b7dd91978dcc40a629e216"
size = 61041
yanked = false
permissions = { network = ["https://api.frankfurter.app"], cache = true, clipboard = false, notifications = false, commands = false }

[[versions]]
version = "1.0.2"
api_version = "^1.0"
source_commit = "02c4b78b55859cd56dcd422fb8916a2b69347e4c"
asset_url = "https://github.com/rslauncher/rayslash-module-currency/releases/download/v1.0.2/rayslash.currency-1.0.2.tar.zst"
sha256 = "bca754b037938b407e41c7425cec864b347abfe71b7d3236db8610fe5c45fa2b"
size = 65465
yanked = false
permissions = { network = ["https://api.frankfurter.dev"], cache = true, clipboard = false, notifications = false, commands = false }

[[versions]]
version = "1.0.3"
api_version = "^1.0"
source_commit = "389c135f814338f31d9bc1585b478508824daebe"
asset_url = "https://github.com/rslauncher/rayslash-module-currency/releases/download/v1.0.3/rayslash.currency-1.0.3.tar.zst"
sha256 = "e325a5802f061c8fcdda7dec8e66b80d81ab9ecd1875e18ff5091acabe6328c0"
size = 56565
yanked = false
permissions = { network = ["https://api.frankfurter.dev"], cache = true, clipboard = false, notifications = false, commands = false }

[[versions]]
version = "1.0.4"
api_version = "^1.0"
source_commit = "cb8cc8e89d774d628d9da9249f22cfd5098bb4a0"
asset_url = "https://github.com/rslauncher/rayslash-module-currency/releases/download/v1.0.4/rayslash.currency-1.0.4.tar.zst"
sha256 = "d00f0f3cb3a59384fc47a9bdf72b84e954c83f1aae40ed46b975ac52c94d6541"
size = 56434
yanked = false
permissions = { network = ["https://api.frankfurter.dev"], cache = true, clipboard = false, notifications = false, commands = false }

[[versions]]
version = "1.0.5"
api_version = "^1.0"
source_commit = "a14de1032f9c2c3cbbb6fdcfae52af95614ccf4c"
asset_url = "https://github.com/rslauncher/rayslash-module-currency/releases/download/v1.0.5/rayslash.currency-1.0.5.tar.zst"
sha256 = "64bc37f433009440d390364114d6d9667be9778725bcf732435004e6fdbfa6e0"
size = 57504
yanked = false
permissions = { network = ["https://api.frankfurter.dev"], cache = true, clipboard = false, notifications = false, commands = false }
